config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :comments
  resources :votes
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts
  has_and_belongs_to_many :users
  validates :title, uniqueness: true, presence: true, length: { in: 3..20 }
  validates :description, presence: true
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]

  # GET /communities or /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: "Community was successfully created." }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy!

    respond_to do |format|
      format.html { redirect_to communities_path, status: :see_other, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.expect(community: [ :title, :description ])
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<div id="<%= dom_id community %>">
  <p>
    <strong>Title:</strong>
    <%= community.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= community.description %>
  </p>

</div>

app/views/communities/_form.html.erb
<%= form_with(model: community) do |form| %>
  <% if community.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<% content_for :title, "Editing community" %>

<h1>Editing community</h1>

<%= render "form", community: @community %>

<br>

<div>
  <%= link_to "Show this community", @community %> |
  <%= link_to "Back to communities", communities_path %>
</div>

app/views/communities/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Communities" %>

<h1>Communities</h1>

<div id="communities">
  <% @communities.each do |community| %>
    <%= render community %>
    <p>
      <%= link_to "Show this community", community %>
    </p>
  <% end %>
</div>

<%= link_to "New community", new_community_path %>

app/views/communities/new.html.erb
<% content_for :title, "New community" %>

<h1>New community</h1>

<%= render "form", community: @community %>

<br>

<div>
  <%= link_to "Back to communities", communities_path %>
</div>

app/views/communities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @community %>

<div>
  <%= link_to "Edit this community", edit_community_path(@community) %> |
  <%= link_to "Back to communities", communities_path %>

  <%= button_to "Destroy this community", @community, method: :delete %>
</div>